/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project2;

public class App {

    public static void main(String[] args) {
        ArrayQueue<String> list = new ArrayQueue<>();
        list.add("item00");
        list.add("item01");
        list.remove();
        list.add("item02");
        list.add("item03");
        list.remove();
        list.add("item04");
        list.add("item05");
        list.remove();
        list.add("item06");
        list.displayAll();
    }

    
}
