/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

public class App {

    public static void main(String[] args) {
        ArrayStack<String> list = new ArrayStack<>();
        list.push("item00");
        list.push("item01");
        list.push("item02");
        list.push("item03");
        list.pop();
        list.displayOne(2);
        list.push("item04");
        list.push("item05");
        list.displayPeek();
        list.push("item06");
        list.pop();
        list.push("item07");
        list.displayAll();
    }

    
}
