/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

public class App {

    public static void main(String[] args) {
        
        ArrList<String> list = new ArrList<String>();
        list.insertLast(new String("Obj01"));
        list.insertLast(new String("Obj02"));        
        list.delete(2);
        list.insertLast(new String("Obj03"));
        list.insertLast(new String("Obj04"));
        list.delete(2);
        list.insertLast(new String("Obj05"));
        list.displayAll();

    }

}
