/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

public class App {

    public static void main(String[] args) {
        
        ArrList<NObject> list = new ArrList<NObject>();
        list.insertLast(new NObject("Obj01"));
        list.insertLast(new NObject("Obj02"));        
        list.delete(2);
        list.insertLast(new NObject("Obj03"));
        list.insertLast(new NObject("Obj04"));
        list.delete(2);
        list.insertLast(new NObject("Obj05"));
        list.displayAll();

    }

}
