/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import java.util.ArrayList;

public class App {

    public static void main(String[] args) {
        
        ArrList<String> list = new ArrList<String>();
        list.insertLast(new String("Obj01"));
        list.insertLast(new String("Obj02"));        
        list.delete(2);
        list.insertLast(new String("Obj03"));
        list.insertLast(new String("Obj04"));
        list.delete(2);
        list.insertLast(new String("Obj05"));
        list.displayAll();
        list.removeAll();

        ArrList<Integer> list2 = new ArrList<Integer>();
        list2.insertLast(1);
        list2.insertLast(2);
        list2.delete(2);
        list2.insertLast(3);
        list2.insertLast(4);
        list2.delete(2);
        list2.insertLast(5);
        list2.displayAll();
        list2.removeAll();
    }

}
