/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project3;

public class App {

    public static void main(String[] args) {

        CList<String> list = new CList<String>();
        list.insert("item00");
        list.insert("item01");
        list.insert("item02");
        list.insert("item03");
        list.delete("item02");
        list.insert("item04");
        list.insert("item05");
        list.delete("item00");
        list.insert("item06");
        list.displayAll();
        
    }

}
