/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project1;

public class App {

    public static void main(String[] args) {

        try {
            ListStack<String> list = new ListStack<>();
            list.push("item00");
            list.push("item01");
            list.pop();
            list.push("item02");
            list.push("item03");
            list.pop();
            list.push("item04");
            list.push("item05");
            list.push("item06");
            list.displayAll();
        } catch (CloneNotSupportedException e) {
            e.printStackTrace();
        }

    }

    
}
